import type { Metadata } from "next";
import { Poppins } from "next/font/google"; //Geist, Geist_Mono,
import "./styles/globals.css";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "CM Advogatus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/*<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>*/}
      <body className={`${poppins} antialiased 2xl:text-2xl`}>
        {children}
      </body>
    </html>
  );
}