import type { Metadata } from "next";
import { Poppins } from "next/font/google"; //Geist, Geist_Mono,
import "@/app/styles/globals.css";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

const poppins = Poppins({
  weight: ["400","500", "600","700", "800", "900"],
  style: ["normal","italic"] ,
  subsets: ["latin"]
});


export const metadata: Metadata = {
  title: "CM Advogatus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      {/*<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>*/}
      <body className={`${poppins} antialiased xl:text-xl`}>
        {children}
      </body>
    </html>
  );
}